//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMCCPCSaveTransferTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaloMCCPCSaveTransferTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00_sandbox-0_010.bin
        ///assault-0_010.bin
        ///assault-1_010.bin
        ///assault-2_010.bin
        ///assault-3_010.bin
        ///ctf-0_010.bin
        ///ctf-1_010.bin
        ///ctf-2_010.bin
        ///ctf-3_010.bin
        ///h3_2v2_team_hardcoreSlayer_25kills.bin
        ///h3_4v4_hardcoreBall_250points.bin
        ///h3_4v4_hardcoreFlag_heretic_5points.bin
        ///h3_4v4_hardcoreFlag_narrows_3points.bin
        ///h3_4v4_hardcoreFlag_pit_3points.bin
        ///h3_4v4_hardcoreKing_250points.bin
        ///h3_4v4_hardcoreSlayer_50kills.bin
        ///h3_4v4_hardcoreSlayer_construct_50kills.bin
        ///h3_ffa_hardcoreSlayer_12min.bin
        ///infection-0_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Halo3GameTypeIgnoreList {
            get {
                return ResourceManager.GetString("Halo3GameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h3_epitaph_epilogue_bruteshotFix.mvar
        ///h3_hardcoreConstruct.mvar
        ///h3_hardcoreConstruct_ts.mvar
        ///h3_hardcoreFoundry_amplified.mvar
        ///h3_hardcoreFoundry_onslaught.mvar
        ///h3_hardcoreGuardian.mvar
        ///h3_hardcoreHeretic.mvar
        ///h3_hardcoreHeretic_ffa.mvar
        ///h3_hardcoreNarrows.mvar
        ///h3_hardcorePit.mvar
        ///year2_sandtrap_sandtarp_012.mvar
        ///year2_snowbound_boundless_012.mvar
        ///year2_the_pit_pitstop_012.mvar.
        /// </summary>
        public static string Halo3MapIgnoreList {
            get {
                return ResourceManager.GetString("Halo3MapIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00_basic_editing_054.bin
        ///2nvasion_slayer_054.bin
        ///3nvasion_054.bin
        ///3nvasion_boneyard_054.bin
        ///3nvasion_dlc_054.bin
        ///3nvasion_spire_054.bin
        ///assault_054.bin
        ///assault_neutral_bomb_054.bin
        ///assault_one_bomb_054.bin
        ///ctf_054.bin
        ///ctf_1flag_054.bin
        ///ctf_multiteam_054.bin
        ///ctf_neutralflag_054.bin
        ///headhunter_054.bin
        ///headhunter_pro_054.bin
        ///hr_4v4_team_3plots_dmr_ar_500points_tu.bin
        ///hr_4v4_team_assault_dmr_ar_3points_tu.bin
        ///hr_4v4_team_crazyKing_dmr_ar_150points_tu.bin
        ///hr_4v4_team_headhunter_dmr_ar_50points_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HaloReachGameTypeIgnoreList {
            get {
                return ResourceManager.GetString("HaloReachGameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beaver_creek_cl_031.mvar
        ///damnation_cl_031.mvar
        ///hang_em_high_cl_031.mvar
        ///headlong_cl_031.mvar
        ///hr_forgeWorld_asylum.mvar
        ///hr_forgeWorld_hemorrhage.mvar
        ///hr_forgeWorld_paradiso.mvar
        ///hr_forgeWorld_pinnacle.mvar
        ///hr_forgeWorld_theCage.mvar
        ///prisoner_cl_031.mvar
        ///timberland_cl_031.mvar.
        /// </summary>
        public static string HaloReachMapIgnoreList {
            get {
                return ResourceManager.GetString("HaloReachMapIgnoreList", resourceCulture);
            }
        }
    }
}
