//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaloMCCPCSaveTransferTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HaloMCCPCSaveTransferTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H2A_001_001_basic_editing_137.bin
        ///H2A_100_100_Slayer_BASE_TeamSlayer_137.bin
        ///H2A_100_150_Slayer_Pro_137.bin
        ///H2A_100_200_Slayer_FFA_137.bin
        ///H2A_100_250_Slayer_BR_137.bin
        ///H2A_100_300_Slayer_BR_FFA_137.bin
        ///H2A_100_350_Slayer_Elimination_137.bin
        ///H2A_100_400_Slayer_Phantom_Elimination_137.bin
        ///H2A_100_450_Slayer_Phantoms_137.bin
        ///H2A_100_500_Slayer_Team_Phantoms_137.bin
        ///H2A_100_550_Slayer_Rockets_137.bin
        ///H2A_100_600_Slayer_Snipers_137.bin
        ///H2A_100_650_Slayer_Team_Snipers_137.bin
        ///H2A_100_700_Slayer_Swor [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Halo2AGameTypeIgnoreList {
            get {
                return ResourceManager.GetString("Halo2AGameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bloodline_classic.mvar
        ///lockdown_classic.mvar
        ///remnant_classic.mvar
        ///shrine_classic.mvar
        ///stonetown_classic.mvar
        ///warlord_classic.mvar
        ///zenith_classic.mvar.
        /// </summary>
        public static string Halo2AMapIgnoreList {
            get {
                return ResourceManager.GetString("Halo2AMapIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01_slayer.bin
        ///02_team_slayer.bin
        ///03_rockets.bin
        ///04_swords.bin
        ///05_snipers.bin
        ///06_phantoms.bin
        ///07_team_phantoms.bin
        ///08_elimination.bin
        ///09_multi_flag_ctf.bin
        ///10_ctf_classic.bin
        ///11_01_1_flag_ctf.bin
        ///12_1_flag_ctf_fast.bin
        ///13_king.bin
        ///14_team_king.bin
        ///15_phantom_king.bin
        ///16_crazy_king.bin
        ///17_team_crazy_king.bin
        ///18_oddball.bin
        ///19_rocketball.bin
        ///20_swordball.bin
        ///21_team_ball.bin
        ///22_low_ball.bin
        ///23_fiesta.bin
        ///24_2_on_1.bin
        ///25_3_on_1.bin
        ///26_ninjanaut.bin
        ///27_phantom_fodder.bin
        ///28_dreadnaut. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Halo2GameTypeIgnoreList {
            get {
                return ResourceManager.GetString("Halo2GameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00_sandbox-0_010.bin
        ///assault-0_010.bin
        ///assault-1_010.bin
        ///assault-2_010.bin
        ///assault-3_010.bin
        ///ctf-0_010.bin
        ///ctf-1_010.bin
        ///ctf-2_010.bin
        ///ctf-3_010.bin
        ///h3_2v2_team_hardcoreSlayer_25kills.bin
        ///h3_4v4_hardcoreBall_250points.bin
        ///h3_4v4_hardcoreFlag_heretic_5points.bin
        ///h3_4v4_hardcoreFlag_narrows_3points.bin
        ///h3_4v4_hardcoreFlag_pit_3points.bin
        ///h3_4v4_hardcoreKing_250points.bin
        ///h3_4v4_hardcoreSlayer_50kills.bin
        ///h3_4v4_hardcoreSlayer_construct_50kills.bin
        ///h3_ffa_hardcoreSlayer_12min.bin
        ///infection-0_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Halo3GameTypeIgnoreList {
            get {
                return ResourceManager.GetString("Halo3GameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h3_epitaph_epilogue_bruteshotFix.mvar
        ///h3_hardcoreConstruct.mvar
        ///h3_hardcoreConstruct_ts.mvar
        ///h3_hardcoreFoundry_amplified.mvar
        ///h3_hardcoreFoundry_onslaught.mvar
        ///h3_hardcoreGuardian.mvar
        ///h3_hardcoreHeretic.mvar
        ///h3_hardcoreHeretic_ffa.mvar
        ///h3_hardcoreNarrows.mvar
        ///h3_hardcorePit.mvar
        ///year2_sandtrap_sandtarp_012.mvar
        ///year2_snowbound_boundless_012.mvar
        ///year2_the_pit_pitstop_012.mvar.
        /// </summary>
        public static string Halo3MapIgnoreList {
            get {
                return ResourceManager.GetString("Halo3MapIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01_slayer.bin
        ///02_team_slayer.bin
        ///03_classic_slayer.bin
        ///04_classic_slayer_pro.bin
        ///05_classic_phantoms.bin
        ///05_classic_team_slayer.bin
        ///06_classic_elimination.bin
        ///08_classic_endurance.bin
        ///09_classic_rockets.bin
        ///10_classic_snipers.bin
        ///11_ctf.bin
        ///12_classic_ctf.bin
        ///13_classic_invasion.bin
        ///14_classic_iron_ctf.bin
        ///15_classic_ctf_pro.bin
        ///16_king.bin
        ///17_crazy_king.bin
        ///18_team_king.bin
        ///19_classic_king.bin
        ///20_classic_king_pro.bin
        ///21_classic_crazy_king.bin
        ///22_classic_team_king.bin
        ///23_oddball.bin
        ///2 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HaloCEGameTypeIgnoreList {
            get {
                return ResourceManager.GetString("HaloCEGameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00_basic_editing_054.bin
        ///2nvasion_slayer_054.bin
        ///3nvasion_054.bin
        ///3nvasion_boneyard_054.bin
        ///3nvasion_dlc_054.bin
        ///3nvasion_spire_054.bin
        ///assault_054.bin
        ///assault_neutral_bomb_054.bin
        ///assault_one_bomb_054.bin
        ///ctf_054.bin
        ///ctf_1flag_054.bin
        ///ctf_multiteam_054.bin
        ///ctf_neutralflag_054.bin
        ///headhunter_054.bin
        ///headhunter_pro_054.bin
        ///hr_4v4_team_3plots_dmr_ar_500points_tu.bin
        ///hr_4v4_team_assault_dmr_ar_3points_tu.bin
        ///hr_4v4_team_crazyKing_dmr_ar_150points_tu.bin
        ///hr_4v4_team_headhunter_dmr_ar_50points_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HaloReachGameTypeIgnoreList {
            get {
                return ResourceManager.GetString("HaloReachGameTypeIgnoreList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beaver_creek_cl_031.mvar
        ///damnation_cl_031.mvar
        ///hang_em_high_cl_031.mvar
        ///headlong_cl_031.mvar
        ///hr_forgeWorld_asylum.mvar
        ///hr_forgeWorld_hemorrhage.mvar
        ///hr_forgeWorld_paradiso.mvar
        ///hr_forgeWorld_pinnacle.mvar
        ///hr_forgeWorld_theCage.mvar
        ///prisoner_cl_031.mvar
        ///timberland_cl_031.mvar.
        /// </summary>
        public static string HaloReachMapIgnoreList {
            get {
                return ResourceManager.GetString("HaloReachMapIgnoreList", resourceCulture);
            }
        }
    }
}
